### ISSUE TITLE
python-xmp-toolkit/python-xmp-toolkit was archived

### ISSUE THREAD

**Issue by zougloub** [exmakhina/python-xmp-toolkit#1]
While it hasn't been updated in a while, it doesn't mean it can't continue to exist.

**Comment by zougloub** [comment]
I invited here (for discussion) the maintainers of python-xmp-toolkit/python-xmp-toolkit  @kapadia & @lnielsen, @quintusdias who authored most recent commits in the upstream repo, and the exempi maintainer @hfiguiere.

First I wonder why it was archived, then, any chance it can be de-archived and maintained alive, given there are other packages depending on it, the code is not so bad, and there's already infra in place.

**Comment by zougloub** [comment]
In case the highlight here lacked visibility, I just contacted @lnielsen by e-mail.

**Comment by zougloub** [comment]
I just filed https://github.com/pypi/support/issues/2638, just in case.

**Comment by lnielsen** [comment]
Hi Jerome,

Thanks for reaching out. I haven't been active on the repository for about 8-10 years now. I originally developed the library for ESO which I left in 2012, and got contacted by @quintusdias who took on further development but who have also been somewhat inactive for the past 6 years.

I noticed on the repository that people were still creating issues on the repository and waiting for reply, so I wanted to quickly at least indicate to people that the project is completely inactive with no maintenance. That's why I archived it.

Libexempi that the library depends on seems also to have stopped maintenance as well (last commit 5 years ago). In addition, https://github.com/adobe/XMP-Toolkit-SDK is now building on all systems as well and is BSD licensed. Thus, I can definitely unarchive the project and add you as maintainer, but I'm wondering if it's not better to let the project die, so that dependent projects can remove their dependency on it. 

Cheers,
Lars

**Comment by FriedrichFroebel** [comment]
> Libexempi that the library depends on seems also to have stopped maintenance as well (last commit 5 years ago)

At least https://gitlab.freedesktop.org/libopenraw/exempi/-/blob/master/NEWS?ref_type=heads seems to indicate that development is still somehow active in the upstream project and is available under the same license as the Adobe repository as it basically is a Unix-compatible variant.

**Comment by zougloub** [comment]
For some reason I had completely missed the notification from @lnielsen  a while ago. Yeah, exempi is not dead. And I am willing to be added as maintainer of the upstream python-xmp-toolkit.

**Comment by zougloub** [comment]
Happy new year,  @lnielsen kindly transferred ownership of the upstream project so we'll do our best at keeping it alive. I unarchived it. This issue can be closed. This fork will now be a contributor fork.
